# Create
POST {{host}}/BundleType
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "Bundle"
}

### Update
PUT {{host}}/BundleType/6b105f90-bc92-407f-a20e-e2e5675b39a5
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "250 Min Plud 5GB"
}

#### Delete
DELETE {{host}}/BundleType/6b105f90-bc92-407f-a20e-e2e5675b39a5
Authorization: Bearer {{token}}

#### Get All
GET {{host}}/BundleType/getall
Authorization : Bearer {{token}}

#### Get Paginated
GET {{host}}/BundleType/getpaginated?page=1&pageSize=10
Authorization : Bearer {{token}}

#### Get By Id
GET {{host}}/BundleType/6b105f90-bc92-407f-a20e-e2e5675b39a5
Authorization : Bearer {{token}}
