# @name login
POST {{host}}/login
Content-Type: application/json

{
  "Email": "01710870813",
  "Password": "MAriful1!"
}

### Register
POST {{host}}/register
Content-Type: application/json

{
  "UserName" : "marif2",
  "Password" : "MAriful1!",
  "Email" : "maruf2@gmail.com"
}

### Refresh Token
POST {{host}}/refresh
Content-Type: application/json

{
  "refreshToken": "{{login.response.body.$.refreshToken}}"
}

### Confirm Email
GET {{host}}/confirmEmail?userId={{login.response.body.$.userId}}&code={{login.response.body.$.code}}

### Resend Confirm Email
POST {{host}}/resendConfirmationEmail
Content-Type: application/json

{
  "email": "maruf2@gmail.com"
}

### Forgot Password
POST {{host}}/forgotPassword
Content-Type: application/json

{
  "email": "maruf2@gmail.com"
}

### Reset Password
POST {{host}}/resetPassword
Content-Type: application/json

{
  "email": "",
  "resetCode": "",
  "newPassword": "MAriful1!"
}

### Manage 2fa
POST {{host}}/manage/2fa
Authorization : Bearer {{login.response.body.$.accessToken}}
Content-Type: application/json

{

}


### Sample Request
GET {{host}}/
Authorization: Bearer {{login.response.body.$.accessToken}}

