# Create Offer
POST {{host}}/offer
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Title": "30 GB Data",
  "Description": "Sample Description",
  "Price": 50.00,
  "Discount": 10.00,
  "ImageUrl": "https://example.com/image.jpg",
  "OfferType": "Drive",
  "BundleTypeId": "c99a681c-f1c3-4911-bfa1-3ab69f9ec1f5",
  "ProcessType": "Auto",
  "Rank": 1,
  "ExpiredAt": "2024-10-18T00:00:00Z",
  "Code": "SAMPLECODE",
  "Remarks": "Sample Remarks",
  "FinancialEntityId": "e8b27fdb-89d2-4814-b3c3-3592d643ac99"
}

### Get Offer By Id
GET {{host}}/offer/fadb4a76-70ee-46f0-9fa2-5227ac68a9da
Authorization: Bearer {{token}}

### Update Offer
PUT {{host}}/offer/fadb4a76-70ee-46f0-9fa2-5227ac68a9da
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Title": "20 GB Data",
  "Description": "Sample Description",
  "Price": 50.00,
  "Discount": 10.00,
  "ValidityInHours": 24,
  "ImageUrl": "https://example.com/image.jpg",
  "OfferType": "Drive",
  "BundleTypeId": "fadb4a76-70ee-46f0-9fa2-5227ac68a9da",
  "ProcessType": "Auto",
  "Rank": 1,
  "ExpiredAt": "2024-08-09T00:00:00Z",
  "Code": "SAMPLECODE",
  "Remarks": "Sample Remarks",
  "FinancialEntityId": "0191291d-1f47-ce65-0ff2-f6d1322931a1"
}

### Delete Offer
DELETE {{host}}/offer/fadb4a76-70ee-46f0-9fa2-5227ac68a9da
Authorization : Bearer {{ token }}

### Get All Offers
GET {{host }}/offer/getAll
Authorization : Bearer {{ token }}
