export const ActionTypes = {
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    SIGN_IN_ERROR: 'SIGN_IN_ERROR',

    FETCH_FINANCIAL_ENTITIES: 'FETCH_FINANCIAL_ENTITIES',
    FETCH_OPERATOR: 'FETCH_OPERATORS',
    FETCH_BANK: 'FETCH_BANKS',
    CREATE_FINANCIAL_ENTITY: 'CREATE_FINANCIAL_ENTITY',
    UPDATE_FINANCIAL_ENTITY: 'UPDATE_FINANCIAL_ENTITY',
    DELETE_FINANCIAL_ENTITY: 'DELETE_FINANCIAL_ENTITY',

    FETCH_OFFERS: 'FETCH_OFFERS',
    CREATE_OFFERS: 'CREATE_OFFERS',
    UPDATE_OFFERS: 'UPDATE_OFFERS',
    DELETE_OFFERS: 'DELETE_OFFERS',

    FETCH_BUNDLE_TYPES: 'FETCH_BUNDLE_TYPES',
    CREATE_BUNDLE_TYPES: 'CREATE_BUNDLE_TYPES',
    UPDATE_BUNDLE_TYPES: 'UPDATE_BUNDLE_TYPES',
    DELETE_BUNDLE_TYPES: 'DELETE_BUNDLE_TYPES',

    FETCH_BY_TRANSACTION_ID: 'FETCH_BY_TRANSACTION_ID',
    CHECK_BALANCE: 'CHECK_BALANCE',
    ADD_BALANCE: 'ADD_BALANCE',
    BUY_OFFERS: 'BUY_OFFERS',
    FETCH_TRANSACTIONS: 'FETCH_TRANSACTIONS',
    RECHARGE_TRANSACTIONS: 'RECHARGE_TRANSACTIONS',

    FETCH_NOTICES: 'FETCH_NOTICES',
    CREATE_NOTICE: 'CREATE_NOTICE',
    UPDATE_NOTICE: 'UPDATE_NOTICE',
    DELETE_NOTICE: 'DELETE_NOTICE',

    FETCH_USERS: 'FETCH_USERS',
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    GET_USER: 'GET_USER',
    GET_BY_ID_USER: 'GET_BY_ID_USER',
};