export const ActionTypes = {
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    SIGN_IN_ERROR: 'SIGN_IN_ERROR',

    FETCH_USERS: 'FETCH_USERS',
    FETCH_ROLES: 'FETCH_ROLES',
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
    DELETE_USER: 'DELETE_USER',
    GET_BY_NUMBER_USER: 'GET_BY_NUMBER_USER',
    GET_USER: 'GET_USER',

    FETCH_SLIDERS: 'FETCH_SLIDERS',
    CREATE_SLIDER: 'CREATE_SLIDER',
    UPDATE_SLIDER: 'UPDATE_SLIDER',
    DELETE_SLIDER: 'DELETE_SLIDER',

    FETCH_MEDIAS: 'FETCH_MEDIAS',
    CREATE_MEDIA: 'CREATE_MEDIA',
    DELETE_MEDIA: 'DELETE_MEDIA',

    FETCH_SETTINGS: 'FETCH_SLIDERS',
    CREATE_SETTING: 'CREATE_SETTING',
    UPDATE_SETTING: 'UPDATE_SETTING',
};