export const ActionTypes = {
    LOG_IN: 'LOG_IN',
    LOG_OUT: 'LOG_OUT',
    REGISTER: 'REGISTER',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    LOGIN_IN_ERROR: 'LOG_IN_ERROR',

    FETCH_WEATHERS: 'FETCH_WEATHERS',
};